.mode box
.headers on
.excel
SELECT EVENTS.DATEID, EVENTS.USERID, EVENTS.TICKET, EVENTS.EVENT, MARKSMX2.DAILY, MARKSMX2.WEEKLY, MARKSMX2.SEMESTER, MARKSMX2.INCMX2, MARKSMX2.CORRMX2, MARKSMX2.ATINCMX2, MARKSMX3.DAILY, MARKSMX3.WEEKLY, MARKSMX3.SEMESTER, MARKSMX3.INCMX3, MARKSMX3.CORRMX3, MARKSMX3.ATINCMX3
FROM EVENTS
LEFT JOIN MARKSMX2
ON EVENTS.DATEID = MARKSMX2.DATEID
LEFT JOIN MARKSMX3
ON EVENTS.DATEID = MARKSMX3.DATEID;